ref = {
    "a": 0b1 << 0,
    "b": 0b1 << 1,
    "c": 0b1 << 2,
    "d": 0b1 << 3,
    "e": 0b1 << 4,
    "f": 0b1 << 5,
    "g": 0b1 << 6,
    "h": 0b1 << 7,
    "i": 0b1 << 8,
    "j": 0b1 << 9,
    "k": 0b1 << 10,
    "l": 0b1 << 11,
    "m": 0b1 << 12,
    "n": 0b1 << 13,
    "o": 0b1 << 14,
    "p": 0b1 << 15,
    "q": 0b1 << 16,
    "r": 0b1 << 17,
    "s": 0b1 << 18,
    "t": 0b1 << 19,
    "u": 0b1 << 20,
    "v": 0b1 << 21,
    "w": 0b1 << 22,
    "x": 0b1 << 23,
    "y": 0b1 << 24,
    "z": 0b1 << 25,
    "/": 0b1 << 26,
    "-": 0b1 << 27,
}
rules = {
    # 声母
    "zh": "zh",
    "ch": "ch",
    "sh": "sh",
    # 韵母
    "ai": "ai",
    "ei": "ei",
    "ao": "ao",
    "ou": "ou",
    "an": "an",
    "en": "en",
    "ang": "ang",
    "eng": "eng",
    "ong": "ong",
    "ve": "ve",
    "er": "er",
    "in": "in",
    "iao": "iao",
    "iou": "iu",
    "ian": "ian",
    "iang": "iang",
    "iong": "iong",
    "ing": "ing",
    "ua": "ua",
    "uai": "uai",
    "ui": "ui",
    "uan": "uan",
    # "uang": "uang", #和guang冲突
    "ueng": "ueng",
    "ue": "ue",
    "er": "er",
    "un": "un",
    # 韵母间冲突
    "ia-": "ia",
    "ie-": "ie",
    "uo-": "uo",
    # 整体音节
    "zhi": "zhi",
    "chi": "chi",
    "shi": "shi",
    "ri": "ri",
    "zi": "zi",
    "ci": "ci",
    "si": "si",
    "yi": "yi",
    "wu": "wu",
    "yu": "yu",
    "ye": "ye",
    "yue": "yue",
    "yuan": "yuan",
    "yin": "yin",
    "yun": "yun",
    "ying": "ying",
    # 单韵母
    "ba": "ba",
    "bo": "bo",
    "bi": "bi",
    "bu": "bu",
    "pa": "pa",
    "po": "po",
    "pi": "pi",
    "pu": "pu",
    "ma": "ma",
    "mo": "mo",
    "me": "me",
    "mi": "mi",
    "mu": "mu",
    "fa": "fa",
    "fo": "fo",
    "fu": "fu",
    "da": "da",
    "de": "de",
    "di": "di",
    "du": "du",
    "ta": "ta",
    "te": "te",
    "ti": "ti",
    "tu": "tu",
    "nv": "nv",
    "la": "la",
    "le": "le",
    "li": "li",
    "lu": "lu",
    "lv": "lv",
    "ga": "ga",
    "ge": "ge",
    "gu": "gu",
    "ka": "ka",
    "ke": "ke",
    "ku": "ku",
    "ha": "ha",
    "he": "he",
    "hu": "hu",
    "ji": "ji",
    "ju": "ju",
    "qi": "qi",
    "qu": "qu",
    "xi": "xi",
    "xu": "xu",
    "zha": "zha",
    "zhe": "zhe",
    "zhu": "zhu",
    "zhi": "zhi",
    "cha": "cha",
    "che": "che",
    "chu": "chu",
    "chi": "chi",
    "sha": "sha",
    "she": "she",
    "shu": "shu",
    "shi": "shi",
    "ru": "ru",
    "ri": "ri",
    "za": "za",
    "ze": "ze",
    "zu": "zu",
    "zi": "zi",
    "ca": "ca",
    "ce": "ce",
    "cu": "cu",
    "ci": "ci",
    "sa": "sa",
    "se": "se",
    "su": "su",
    "si": "si",
    "ya": "ya",
    "ye": "ye",
    "yi": "yi",
    "yu": "yu",
    "wa": "wa",
    "wo": "wo",
    "wu": "wu",
    # 单韵母与韵母冲突
    "na-": "na",
    "ne-": "ne",
    "ni-": "ni",
    "nu-": "nu",
    "re-": "re",
    # 复韵母
    "bai": "bai",
    "bei": "bei",
    "bao": "bao",
    "pai": "pai",
    "pei": "pei",
    "pao": "pao",
    "pou": "pou",
    "mai": "mai",
    "mei": "mei",
    "mao": "mao",
    "mou": "mou",
    "miu": "miu",
    "fai": "fai",
    "fei": "fei",
    "fou": "fou",
    "dai": "dai",
    "dei": "dei",
    "dui": "dui",
    "dao": "dao",
    "dou": "dou",
    "diou": "diu",
    "tai": "tai",
    "tei": "tei",
    "tui": "tui",
    "tao": "tao",
    "tou": "tou",
    "nei": "nei",
    "nao": "nao",
    "nou": "nou",
    "niu": "niu",
    "nve": "nve",
    "nue": "nue",
    "lai": "lai",
    "lei": "lei",
    "lao": "lao",
    "lou": "lou",
    "liu": "liu",
    "lve": "lve",
    "lue": "lue",
    "gai": "gai",
    "gei": "gei",
    "gui": "gui",
    "gao": "gao",
    "gou": "gou",
    "kai": "kai",
    "kei": "kei",
    "kui": "kui",
    "kao": "kao",
    "kou": "kou",
    "hai": "hai",
    "hei": "hei",
    "hui": "hui",
    "hao": "hao",
    "hou": "hou",
    "jiu": "jiu",
    "jie": "jie",
    "jue": "jue",
    "qiu": "qiu",
    "qie": "qie",
    "que": "que",
    "xiu": "xiu",
    "xie": "xie",
    "xue": "xue",
    "zhai": "zhai",
    "zhei": "zhei",
    "zhui": "zhui",
    "zhao": "zhao",
    "zhou": "zhou",
    "chai": "chai",
    "chui": "chui",
    "chao": "chao",
    "chou": "chou",
    "shai": "shai",
    "shei": "shei",
    "shui": "shui",
    "shao": "shao",
    "shou": "shou",
    "rui": "rui",
    "rao": "rao",
    "rou": "rou",
    "zai": "zai",
    "zei": "zei",
    "zui": "zui",
    "zao": "zao",
    "zou": "zou",
    "cai": "cai",
    "cui": "cui",
    "cao": "cao",
    "cou": "cou",
    "sai": "sai",
    "sui": "sui",
    "sao": "sao",
    "sou": "sou",
    "yao": "yao",
    "you": "you",
    "yue": "yue",
    "wai": "wai",
    "wei": "wei",
    # 复韵母冲突
    "bie-": "bie",
    "pie-": "pie",
    "mie-": "mie",
    "die-": "die",
    "tie-": "tie",
    "nai-": "nai",
    "nie-": "nie",
    "lie-": "lie",
    # 前鼻韵母
    "ban": "ban",
    "ben": "ben",
    "bin": "bin",
    "pan": "pan",
    "pen": "pen",
    "pin": "pin",
    "man": "man",
    "men": "men",
    "min": "min",
    "fan": "fan",
    "fen": "fen",
    "dan": "dan",
    "den": "den",
    "dun": "dun",
    "tan": "tan",
    "tun": "tun",
    "nen": "nen",
    "nin": "nin",
    "lan": "lan",
    "lin": "lin",
    "lun": "lun",
    "gun": "gun",
    "kan": "kan",
    "ken": "ken",
    "kun": "kun",
    "han": "han",
    "hen": "hen",
    "hun": "hun",
    "jin": "jin",
    "jun": "jun",
    "qin": "qin",
    "qun": "qun",
    "xin": "xin",
    "xun": "xun",
    "zhan": "zhan",
    "zhen": "zhen",
    "zhun": "zhun",
    "chan": "chan",
    "chen": "chen",
    "chun": "chun",
    "shan": "shan",
    "shen": "shen",
    "shun": "shun",
    "ran": "ran",
    "ren": "ren",
    "run": "run",
    "zan": "zan",
    "zen": "zen",
    "zun": "zun",
    "can": "can",
    "cen": "cen",
    "cun": "cun",
    "san": "san",
    "sen": "sen",
    "sun": "sun",
    "yan": "yan",
    "yin": "yin",
    "yun": "yun",
    "wan": "wan",
    "wen": "wen",
    # 前鼻韵母冲突
    # "nan": "nan", #chord不能
    "gan-": "gan",
    "gen-": "gen",
    # 后鼻韵母
    "bang": "bang",
    "beng": "beng",
    "bing": "bing",
    "pang": "pang",
    "peng": "peng",
    "ping": "ping",
    "mang": "mang",
    "meng": "meng",
    "ming": "ming",
    "fang": "fang",
    "feng": "feng",
    "dang": "dang",
    "deng": "deng",
    "ding": "ding",
    "dong": "dong",
    "tang": "tang",
    "teng": "teng",
    "ting": "ting",
    "tong": "tong",
    "neng": "neng",
    "ning": "ning",
    "nong": "nong",
    "lang": "lang",
    "leng": "leng",
    "ling": "ling",
    "long": "long",
    "gong": "gong",
    "kang": "kang",
    "keng": "keng",
    "kong": "kong",
    "hang": "hang",
    "heng": "heng",
    "hong": "hong",
    "jing": "jing",
    "qing": "qing",
    "xing": "xing",
    "zhang": "zhang",
    "zheng": "zheng",
    "zhong": "zhong",
    "chang": "chang",
    "cheng": "cheng",
    "chong": "chong",
    "shang": "shang",
    "sheng": "sheng",
    "rang": "rang",
    "reng": "reng",
    "rong": "rong",
    "zang": "zang",
    "zeng": "zeng",
    "zong": "zong",
    "cang": "cang",
    "ceng": "ceng",
    "cong": "cong",
    "sang": "sang",
    "seng": "seng",
    "song": "song",
    "yang": "yang",
    "ying": "ying",
    "yong": "yong",
    "wang": "wang",
    "weng": "weng",
    # 后鼻韵母冲突 这些都不能直接chord哇
    # "nang": "nang",
    # "gang": "gang",
    # "geng": "geng",
    # 三拼音节
    "bian": "bian",
    "biao": "biao",
    "pian": "pian",
    "piao": "piao",
    "mian": "mian",
    "miao": "miao",
    "dian": "dian",
    "diao": "diao",
    "duan": "duan",
    "tian": "tian",
    "tiao": "tiao",
    "tuan": "tuan",
    "niang": "niang",
    "niao": "niao",
    "nuan": "nuan",
    "lian": "lian",
    "liang": "liang",
    "liao": "liao",
    "luan": "luan",
    "gua": "gua",
    "guai": "guai",
    "kua": "kua",
    "kuai": "kuai",
    "kuan": "kuan",
    "kuang": "kuang",
    "hua": "hua",
    "huai": "huai",
    "huang": "huang",
    "jia": "jia",
    "jian": "jian",
    "jiang": "jiang",
    "jiao": "jiao",
    "jiong": "jiong",
    "juan": "juan",
    "qia": "qia",
    "qian": "qian",
    "qiang": "qiang",
    "qiao": "qiao",
    "qiong": "qiong",
    "quan": "quan",
    "xia": "xia",
    "xian": "xian",
    "xiang": "xiang",
    "xiao": "xiao",
    "xiong": "xiong",
    "xuan": "xuan",
    "zhua": "zhua",
    "zhuai": "zhuai",
    "zhuan": "zhuan",
    "zhuang": "zhuang",
    "chua": "chua",
    "chuai": "chuai",
    "chuan": "chuan",
    "chuang": "chuang",
    "shua": "shua",
    "shuai": "shuai",
    "shuan": "shuan",
    "shuang": "shuang",
    "ruan": "ruan",
    "zuan": "zuan",
    "cuan": "cuan",
    "suan": "suan",
    "yuan": "yuan",
    "huan": "huan",  #! "guang": "guang",
    # 三拼音节冲突
    "dia-": "dia",
    "duo-": "duo",
    "tuo-": "tuo",
    # "nian": "nian",
    "nuo-": "nuo",
    "lia-": "lia",
    "luo-": "luo",
    "guan": "guan",
    "guo-": "guo",
    "kuo-": "kuo",
    "huo-": "huo",
    "zhuo-": "zhuo",
    "chuo-": "chuo",
    "shuo-": "shuo",
    "ruo-": "ruo",
    "zuo-": "zuo",
    "cuo-": "cuo",
    "suo-": "suo",
}

binRule: dict[int, str] = {}
for rule in rules.keys():
    state = 0
    for char in rule:
        if char in ref:
            state += ref[char]
    if state in binRule:
        print("key conflict at: ", rule)
    else:
        binRule[state] = rules[rule]
# print(binRule)
